@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam sequence {
    ParticipantBackgroundColor #F5C84C
    ParticipantBorderColor #F7E19A
}

skinparam {
    BackgroundColor #F8EAD9
    BorderColor #F8EAD9
}

actor User #064D1A
activate User #064D1A

User -> LikeController : addLikeToForum(forumId, username)
activate LikeController #7AC37A

LikeController -> LikeService : addLikeToForum(forumId, username)
activate LikeService #7AC37A

LikeService -> SecurityUtil : isOwnerOrAdmin(username)
activate SecurityUtil #7AC37A

alt#F5C84C #F5C84C99 Not owner or admin
    SecurityUtil -> LikeService : false
    LikeService -> LikeController : throw SecurityException("Forbidden")
    LikeController -> User : ResponseEntity(HttpStatus.FORBIDDEN)
else #F8EAD9 Owner or admin
    SecurityUtil -> LikeService : true
    deactivate SecurityUtil

LikeService -> UserRepository : findById(username)
activate UserRepository #7AC37A

alt#F5C84C #F5C84C99 User not found
    UserRepository -> LikeService : null
    LikeService -> LikeController : throw RecordNotFoundException("User not found")
    LikeController -> User : ResponseEntity(HttpStatus.NOT_FOUND)
else #F8EAD9 User found
    UserRepository -> LikeService : User
    deactivate UserRepository

    LikeService -> ForumRepository : findById(forumId)
    activate ForumRepository #7AC37A

    alt#F5C84C #F5C84C99 Forum not found
        ForumRepository -> LikeService : null
        LikeService -> LikeController : throw RecordNotFoundException("Forum not found")
        LikeController -> User : ResponseEntity(HttpStatus.NOT_FOUND)
    else #F8EAD9 Forum found
        ForumRepository -> LikeService : Forum
        deactivate ForumRepository

        LikeService -> LikeRepository : findLikeByUserAndForum(user, forum)
        activate LikeRepository #7AC37A

        alt#F5C84C #F5C84C99 UserLike already exists
            LikeRepository -> LikeService : Like
            LikeService -> LikeController : throw IllegalStateException("Like already exists")
            LikeController -> User : ResponseEntity(HttpStatus.CONFLICT)
        else #F8EAD9 UserLike doesn't exist
            LikeRepository -> LikeService : new Like (user, forum)
            deactivate LikeRepository

            LikeService -> LikeRepository : save(Like)
            activate LikeRepository #7AC37A

            LikeRepository -> LikeService : Like
            deactivate LikeRepository

            LikeService -> LikeController : LikeDto
            deactivate LikeService

            LikeController -> User : ResponseEntity(HttpStatus.OK)
        end
    end
end
end

deactivate LikeController
deactivate User
@enduml