@startuml
'https://plantuml.com/class-diagram

skinparam {
    BackgroundColor #F8EAD9
    BorderColor #F8EAD9
}

class Forum #F5C84C99 {
    - Long id
    - String name
    - String title
    - String text
    - String topic
    - int likesCount
    - int viewsCount
    - int commentsCount
    }

class Comment #F5C84C99 {
    - Long id
    - String name
    - String text
    }

class Like #F5C84C99 {
    - Long id
    }

class View #F5C84C99 {
    - Long id
    }

class User #F5C84C99 {
    - String username
    - String password
    - LocalDDate dob
    - String profilePictureUrl
}

class Profile #F5C84C99 {
    - Long id
    - String bio
    - String name
}

class Review #F5C84C99 {
    - Long id
    - String rewview
    - String name
}

User "1" *--[#064D1A] "1" Profile
User "1" *--[#064D1A] "1" Review
User "1" *--[#064D1A] "0..*" Forum

Forum "0..*" *--[#7AC37A] "1" Comment
Forum "0..*" *--[#7AC37A] "1" Like
Forum "0..*" *--[#7AC37A] "1" View

User "0..*" --[#F5C84C] "0..*" Comment
User "0..*" --[#F5C84C] "1" Like
User "0..*" --[#F5C84C] "1" View

'Comment "1" *--[#purple] "1" User
'Like "1" *--[#purple] "1" User
'View "1" *--[#purple] "1" User

@enduml
