@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam sequence {
    ParticipantBackgroundColor #F5C84C
    ParticipantBorderColor #F7E19A
}

skinparam {
    BackgroundColor #F8EAD9
    BorderColor #F8EAD9
}

actor User #064D1A
activate User #064D1A

User -> ForumController : process create forum
activate ForumController #7AC37A

ForumController -> ForumService : createForum(forumInputDto, username)
activate ForumService #7AC37A

ForumService -> UserRepository : findById(username)
activate UserRepository #7AC37A

alt#F5C84C #F5C84C99 User not found
    UserRepository -> ForumService : null
    ForumService -> ForumController : throw RecordNotFoundException("User not found")
    ForumController -> User : ResponseEntity(HttpStatus.NOT_FOUND)
end

UserRepository -> ForumService : User
deactivate UserRepository

ForumService -> ForumRepository : save(forum)
activate ForumRepository #lightblue

ForumRepository -> ForumService : Forum
deactivate ForumRepository

ForumService -> ForumService : assignForumToUser(forumDto.getId(), username)
activate UserRepository #lightblue
activate ForumRepository #lightblue

alt#F5C84C #F5C84C99 Forum or User not found
    UserRepository -> ForumService : null
    ForumRepository -> ForumService : null
    ForumService -> ForumController : throw RecordNotFoundException("Forum or User not found")
    ForumController -> User : ResponseEntity(HttpStatus.NOT_FOUND)
end

UserRepository -> ForumService : User
ForumRepository -> ForumService : Forum
deactivate UserRepository
deactivate ForumRepository

ForumService -> ForumRepository : save(forum)
activate ForumRepository #lightblue
ForumRepository -> ForumService : Forum
deactivate ForumRepository

ForumService -> ForumController : ForumDto
deactivate ForumService

ForumController -> User : ResponseEntity(HttpStatus.CREATED)
deactivate ForumController

@enduml